# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Unweave < Formula
  desc "Manage data like you manage code"
  homepage "https://unweave.io/"
  version "0.0.2"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/unweave/unweave/releases/download/v0.0.2/unweave_0.0.2_Darwin_x86_64.tar.gz"
    sha256 "ca1dfb04e0e56b472502649fd99f58c23ec2db9b9e19f8f5e517037e88f05b7c"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/unweave/unweave/releases/download/v0.0.2/unweave_0.0.2_Darwin_arm64.tar.gz"
    sha256 "59d8012a29c16254422edb462e1305a82972f73cee4b710c2e4b1452e4fd6b0f"
  end

  def install
    bin.install "unweave"
  end

  test do
    system "#{bin}/unweave list"
  end
end
