# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Unweave < Formula
  desc "Manage data like you manage code"
  homepage "https://unweave.io/"
  version "0.0.6"
  bottle :unneeded
  depends_on :macos

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/unweave/unweave/releases/download/v0.0.6/unweave_0.0.6_Darwin_x86_64.tar.gz"
      sha256 "1c1d28252fc1503a8c75ad2e20b7bdaf5df74c98f6b15b7d90f5ec825d9fb3a4"
    end
    if Hardware::CPU.arm?
      url "https://github.com/unweave/unweave/releases/download/v0.0.6/unweave_0.0.6_Darwin_arm64.tar.gz"
      sha256 "99aec3ea874f2cea29f12798a751b3a7b8a830894b87aca672c2b9aeccb28080"
    end
  end

  def install
    bin.install "unweave"
  end

  test do
    system "#{bin}/unweave list"
  end
end
